version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - export CI=true
      - export CODEBUILD=true

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  name: agile-artifacts
  secondary-artifacts:
    AgilePostBuild:
      files:
        - '**/*'
      name: agile-artifacts
